services:
  - type: web
    name: consulta-dni-api
    env: python
    buildCommand: |
      apt-get update && apt-get install -y \
        ca-certificates wget gnupg \
        libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon0 \
        libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 \
        libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
        libpangocairo-1.0-0 libpango-1.0-0 libglib2.0-0 libgtk-3-0 libgbm1 \
        lsb-release xdg-utils \
      && pip install -r requirements.txt \
      && playwright install --with-deps
    startCommand: gunicorn app:app
