services:
  - type: web
    name: consulta-dni-api
    env: python
    buildCommand: |
      apt-get update && apt-get install -y chromium
      pip install -r requirements.txt
    startCommand: gunicorn app:app
